# Generated by Django 3.2.8 on 2021-10-22 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='ffl.league')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('year', models.IntegerField(default=2021)),
                ('qb', models.CharField(max_length=25, verbose_name='Quarterback')),
                ('qb_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('qb_points', models.FloatField(default=0.0)),
                ('rb', models.CharField(max_length=25, verbose_name='Running back')),
                ('rb_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('rb_points', models.FloatField(default=0.0)),
                ('wr', models.CharField(max_length=25, verbose_name='Wide receiver')),
                ('wr_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('wr_points', models.FloatField(default=0.0)),
                ('te', models.CharField(max_length=25, verbose_name='Tight end')),
                ('te_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('te_points', models.FloatField(default=0.0)),
                ('defense', models.CharField(max_length=25, verbose_name='Defense')),
                ('defense_id', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('defense_points', models.FloatField(default=0.0)),
                ('total_points', models.FloatField(default=0.0)),
                ('pick_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Picked')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picks', to='ffl.fantasyteam')),
            ],
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='ffl.league'),
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
