# Generated by Django 4.1.2 on 2022-10-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='defense_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='defense_points',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='qb_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='qb_points',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='rb_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='rb_points',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='te_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='te_points',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='wr_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='wr_points',
        ),
        migrations.AlterField(
            model_name='pick',
            name='defense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defense', to='ffl.playerweek'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='qb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterback', to='ffl.playerweek'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='rb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_back', to='ffl.playerweek'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='te',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tight_end', to='ffl.playerweek'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='wr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wide_receiver', to='ffl.playerweek'),
        ),
    ]
