# Generated by Django 3.2.8 on 2021-10-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='year',
            new_name='season',
        ),
        migrations.AlterField(
            model_name='fantasyteam',
            name='name',
            field=models.CharField(default='default name', max_length=50),
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
