# Generated by Django 3.2.8 on 2021-11-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0002_auto_20211025_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.CharField(default='', max_length=5, verbose_name='Position')),
                ('team', models.CharField(default='', max_length=5, verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('points', models.FloatField(default=0.0, verbose_name='Points')),
                ('passing_yds', models.IntegerField(default=0, verbose_name='Passing Yards')),
                ('passing_tds', models.IntegerField(default=0, verbose_name='Passing Touchdowns')),
                ('passing_ints', models.IntegerField(default=0, verbose_name='Passing Interceptions')),
                ('rushing_yds', models.IntegerField(default=0, verbose_name='Rushing Yards')),
                ('rushing_tds', models.IntegerField(default=0, verbose_name='Rushing Touchdowns')),
                ('receiving_yds', models.IntegerField(default=0, verbose_name='Receiving Yards')),
                ('receiving_tds', models.IntegerField(default=0, verbose_name='Receiving Touchdowns')),
                ('kick_ret_tds', models.IntegerField(default=0, verbose_name='Kick Return Touchdowns')),
                ('two_point_conversions', models.IntegerField(default=0, verbose_name='Two Point Conversions')),
                ('fumbles_lost', models.IntegerField(default=0, verbose_name='Fumbles Lost')),
                ('fumbles_rec_tds', models.IntegerField(default=0, verbose_name='Fumble Recovery Touchdowns')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='ffl.player')),
            ],
        ),
    ]
