# Generated by Django 4.1.3 on 2023-05-19 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0003_alter_defense_fantasy_points_alter_pick_defense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='qb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarterback', to='ffl.playerweek'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='season',
            field=models.IntegerField(default=2023),
        ),
    ]
