# Generated by Django 3.2.8 on 2021-11-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0003_player_playerweek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerweek',
            name='year',
        ),
        migrations.AddField(
            model_name='playerweek',
            name='season',
            field=models.IntegerField(default=2021, verbose_name='Season'),
        ),
    ]
