# Generated by Django 3.2.8 on 2022-01-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0004_auto_20211115_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='defense',
            field=models.CharField(blank=True, max_length=25, verbose_name='Defense'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='qb',
            field=models.CharField(blank=True, max_length=25, verbose_name='Quarterback'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='rb',
            field=models.CharField(blank=True, max_length=25, verbose_name='Running back'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='season',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='pick',
            name='te',
            field=models.CharField(blank=True, max_length=25, verbose_name='Tight end'),
        ),
        migrations.AlterField(
            model_name='pick',
            name='wr',
            field=models.CharField(blank=True, max_length=25, verbose_name='Wide receiver'),
        ),
    ]
