# Generated by Django 4.1.1 on 2022-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0005_auto_20220107_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='playerweek',
            name='season',
            field=models.IntegerField(default=2022, verbose_name='Season'),
        ),
    ]
