# Generated by Django 4.1.1 on 2022-09-30 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0006_alter_player_id_alter_playerweek_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_abbr', models.CharField(default='', max_length=5, verbose_name='Team Name Abbreviation')),
                ('team_name', models.CharField(default='', max_length=30, verbose_name='Team Name')),
                ('team_color', models.CharField(default='', max_length=10, verbose_name='Primary Color')),
                ('team_color2', models.CharField(default='', max_length=10, verbose_name='Secondary Color')),
                ('team_color3', models.CharField(default='', max_length=10, verbose_name='Tertiary Color')),
                ('team_color4', models.CharField(default='', max_length=10, verbose_name='Quaternary Color')),
                ('team_logo', models.CharField(default='', max_length=250, verbose_name='Team Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('season', models.IntegerField(default=2022, verbose_name='Season')),
                ('fantasy_points', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Fantasy Points')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='ffl.team')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ffl.team'),
        ),
    ]
