# Generated by Django 4.1.1 on 2022-10-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl', '0008_alter_defense_fantasy_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='ffl.team'),
        ),
    ]
